CXX = g++
CXXFLAGS	= -std=c++11 -Wall

all: boolean conditionals

clean:
	rm boolean conditionals

boolean: booleanzen.cpp
	$(CXX) $(CXXFLAGS) booleanzen.cpp -o boolean

conditionals: conditionals.cpp
	$(CXX) $(CXXFLAGS) conditionals.cpp -o conditionals
