CXX = g++
CXXFLAGS	= -std=c++11 -Wall

all: boolean conditionals loops

clean:
	rm boolean conditionals loops

boolean: booleanzen_factored.cpp
	$(CXX) $(CXXFLAGS) booleanzen_factored.cpp -o boolean

conditionals: conditionals_factored.cpp
	$(CXX) $(CXXFLAGS) conditionals_factored.cpp -o conditionals

loops: loopsmagicnums_factored.cpp
	$(CXX) $(CXXFLAGS) loopsmagicnums_factored.cpp -o loops
