CXX = g++
CXXFLAGS	= -std=c++11 -Wall

all: boolean conditionals loops

clean:
	rm boolean conditionals loops

boolean: booleanzen.cpp
	$(CXX) $(CXXFLAGS) booleanzen.cpp -o boolean

conditionals: conditionals.cpp
	$(CXX) $(CXXFLAGS) conditionals.cpp -o conditionals

loops: loopsmagicnums.cpp
	$(CXX) $(CXXFLAGS) loopsmagicnums.cpp -o loops
